#ifndef __PRECOMPILED_H__
#define __PRECOMPILED_H__

#include <QApplication>
#include <QTranslator>
#include <QSettings>
#include <QDir>
#include <QFile>
#include <QDebug>
#include <QStandardPaths>
#include <QDate>
#include <QTime>
#include <QDateTime>
#include <QVariant>
#include <QTextCodec>
#include <QCryptographicHash>
#include <QClipboard>
#include <QIcon>
#include <QWidget>
#include <QMainWindow>
#include <QLabel>
#include <QPushButton>
#include <QButtonGroup>
#include <QLineEdit>
#include <QListView>
#include <QTableView>
#include <QTreeView>
#include <QHeaderView>
#include <QTextEdit>
#include <QTextBrowser>
#include <QToolBar>
#include <QStatusBar>
#include <QComboBox>
#include <QRadioButton>
#include <QCheckBox>
#include <QMenu>
#include <QAction>
#include <QACtionGroup>
#include <QMessageBox>
#include <QAbstractListModel>
#include <QAbstractTableModel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QCloseEvent>
#include <QFileDialog>
#include <QThread>

#endif // __PRECOMPILED_H__
